#
# To build locally: https://docs.aws.amazon.com/codebuild/latest/userguide/use-codebuild-agent.html
# ./codebuild_build.sh -i public.ecr.aws/codebuild/amazonlinux2-aarch64-standard:3.0 -a out
#
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo Install started on `date`
      - pip install -r requirements.txt
      - npm install --global cdk && cdk --version
  build:
    commands:
      # For this sample we let the CloudFormation action do the 
      # actual deployment
      - echo Build started on `date`
      - cdk synth
artifacts:
  files:
    - "**/*"
  base-directory: "cdk.out"
  discard-paths: yes
