version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - apt update -y
      - apt install -y curl npm python3-pip
      - npm install --global n
      - n lts
      - hash -r
      - node --version
      - npm install --global cdk
      - cdk --version
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre build started on `date`
      - cdk deploy
  build:
    commands:
      - echo Build started on `date`
      - cdk deploy
    finally:
      - cdk destroy
artifacts:
  files:
    - "**/*"
  base-directory: "cdk.out"
  discard-paths: yes
