version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo Install started on `date`
      # - apt update -y
      # - apt install -y curl npm python3-pip
      # - pip install -r requirements.txt
      # - npm install -g n && n lts && hash -r
      # - node --version
      # - npm install --global cdk
      - npm install --global cdk && cdk --version
  pre_build:
    commands:
      - echo Pre build started on `date`
      - cdk deploy
  build:
    commands:
      - echo Build started on `date`
      - cdk deploy
    finally:
      - cdk destroy
artifacts:
  files:
    - "**/*"
  base-directory: "cdk.out"
  discard-paths: yes
